version: '3.8'

services:

  web:
    build: ./project
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://192.168.160.1:6379/0
      - CELERY_RESULT_BACKEND=redis://192.168.160.1:6379/0

  worker:
    build: ./project
    command: celery worker --app=worker.celery --loglevel=INFO --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://192.168.160.1:6379/0
      - CELERY_RESULT_BACKEND=redis://192.168.160.1:6379/0
      - REDIS_HOST=192.168.160.1
      - REDIS_PORT=6379
      - REDI_DB=0
    depends_on:
      - web

  dashboard:
    build: ./project
    command:  flower --app=worker.celery --port=5555 --broker=redis://192.168.160.1:6379/0
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://192.168.160.1:6379/0
      - CELERY_RESULT_BACKEND=redis://192.168.160.1:6379/0
    depends_on:
      - web
      - worker
      
